Nous somme le binôme qui s’occupe la partie Interface, et nous travaillons principalement sur zDataManager et zDataManagerTest, mais nous avons rencontré un problème que le console affiche toujours que <DataFrame constructor not properly called!>, et nous avons essayé des manières que nous trouvons sur internet, mais jusqu’à maintenant, nous n’avons pas trouver une solution. nous demandons alors une extension de temps, et nous estimons que nous pouvons finir notre partie à 23:59 mardi 28 mars.
Idem pour le classifieur : "ValueError: bad input shape (25521L, 14L)" est le message d'erreur mais la section de code qui a été modifiée n'aurait pas dû rencontrer ce problème étant donné que l'erreur en question concerne y_train qui n'a pas été changé entre temps...